_commit: v0.2.0
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: GabonZ
bmk_repository: https://github.com/gabriel-andreescu/BethesdaModKit.git
components:
  - native
  - plugin_generation
description: Make wards valid again
devbench_api: true
devbench_tests: true
game: skyrim
mcm: true
mutagen_source: src/mutagen/PerfectlyValidWards
native_settings: true
native_source: src/native
pack_assets: false
papyrus_source: src/papyrus
pre_commit: true
project_name: PerfectlyValidWards
