<Project>
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)build/intermediates/dotnet</ArtifactsPath>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
